//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public long Id { get; set; }
        public int TransactionType { get; set; }
        public int BatteryId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Reference { get; set; }
        public int UnitId { get; set; }
    
        public virtual Battery Battery { get; set; }
        public virtual UnitOfItem UnitOfItem { get; set; }
    }
}
